library(cfbfastR)
library(tidyverse)
library(lubridate)
library(dplyr)
library(readr)
#remotes::install_github(repo = "sportsdataverse/cfbfastR")
remotes::install_github(repo = "Kazink36/cfbplotR")
library(cfbplotR)
Sys.setenv(CFBD_API_KEY = "x1C/67YV6Sy98uENGd+tSvJSr82NfDxHFTmWk4QB5wGl2qxogM53QKLB5T4l6kPn")
#Sys.setenv(CFBD_API_KEY = "OMFtwopAS5WexLsewwy5BKQsUIzguwFqGz6KkjiUc6zcpKNYphzld/71fWW7pt8j")
library(stringdist)
library(tidyverse)
library(nnet)
library(mgcv)
library(texreg)
library(aod)
library(xtable)
library(xgboost)
library(readxl)
library(stringr)
library(caret)
library(car)
library(tidyverse)
setwd("C:/Users/harri/OneDrive/Desktop/LTB/CFB Analysis/Data Visualization")

CFB_LOGI_MODEL(ht = c('Georgia'), at=c('Alabama'), input_week = 12)
