---
title: "Matchup Report"
author: "Harrison Eller"
date: "2022-11-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rmarkdown)
library(dplyr)
library(readr)
library(cfbfastR)
#remotes::install_github(repo = "sportsdataverse/cfbfastR")
remotes::install_github(repo = "sportsdataverse/cfbplotR")
library(cfbplotR)
Sys.setenv(CFBD_API_KEY = "x1C/67YV6Sy98uENGd+tSvJSr82NfDxHFTmWk4QB5wGl2qxogM53QKLB5T4l6kPn")
#Sys.setenv(CFBD_API_KEY = "OMFtwopAS5WexLsewwy5BKQsUIzguwFqGz6KkjiUc6zcpKNYphzld/71fWW7pt8j")
library(stringr)
library(tidyverse)
library(nnet)
library(mgcv)
library(texreg)
library(aod)
library(xtable)
library(xgboost)
library(readr)
#library(stringr)
library(caret)
library(car)
library(tidyverse)
library(gt)
#CFB_MODEL <- dget("CFB_MODEL_FUNCTION.R")
CFB_MODEL <- dget("cfb_model_update.R")

```

```{r, include=F}
input_season = 2023
week = 4
include_scarlett = 'yes'

df = data.frame()
#conference = c('SEC')

fbs = cfbd_conferences()
fbs = subset(fbs, classification == 'fbs')
fbs = fbs[1:10,]
fbs_teams = load_cfb_teams()
fbs_teams = subset(fbs_teams, classification == 'fbs')


# team setup
# ht = cfbd_game_info(2022, week = week, conference = conference)$home_team[1]
# home_team_filter = ht = cfbd_game_info(2022, week = week, conference = conference)$home_team[1]
# at = cfbd_game_info(2022, week = week, conference = conference)$away_team[1]
ht=c('Penn State')
at=c("Iowa")
```

```{r, include=F}
# advanced stats by team
stats <- cfbd_stats_season_team(input_season)
TEAMS <- cfbd_stats_season_advanced(input_season)
TEAMS <- inner_join(stats,TEAMS,by = 'team')
TEAMS$Total_YPG <- TEAMS$total_yds / (week-1)
TEAMS$Passing_YPG <- TEAMS$net_pass_yds / (week-1)
TEAMS$Rushing_YPG <- TEAMS$rush_yds / (week-1)
TEAMS$Passing_YPA <- TEAMS$net_pass_yds / TEAMS$pass_atts
TEAMS$Passing_YPC <- TEAMS$net_pass_yds / TEAMS$pass_comps
TEAMS$Rushing_YPA <- TEAMS$rush_yds / TEAMS$rush_atts
TEAMS$third_down_conv_rate<- TEAMS$third_down_convs / TEAMS$third_downs
```


# Betting Information


```{r, echo=F}
# Betting information 
# Betting information 
lines <- cfbd_betting_lines(year = 2023, week = week, team = ht)

line <- subset(lines,provider == "DraftKings")
if (nrow(line) < 1 | is.na(line$over_under[1]) | is.na(line$spread[1]) ){line <- subset(lines,provider == "Bovada")}
# bet$home_score <- ifelse(as.numeric(bet$spread) < 0, as.numeric(bet$over_under) + as.numeric(bet$spread),  as.numeric(bet$over_under) - as.numeric(bet$spread))
# 
# bet$away_score <- as.numeric(bet$over_under) - as.numeric(bet$home_score)



bet <- data.frame(home_score=0,away_score=0,total=0,home_team=0,away_team=0,spread=0, home_conference=0)
bet$total <- as.numeric(line$over_under[1])
bet$spread <- as.numeric(line$spread[1])
bet$home_score <- ifelse(bet$spread  < 0, (bet$total/2)-(bet$spread/2), (bet$total/2)+(bet$spread/2))
bet$away_score <- bet$total - bet$home_score 

bet$home_team <- ht
bet$away_team <- at




bet %>% 
  transmute(Game_Total = total,
      Home_Team = home_team,
            Home_Score = home_score, Away_Score= away_score,
            Away_Team = away_team, Home_Spread = spread) %>% 
  gt() %>%
  #gt_fmt_cfb_logo(columns = c(Conference)) %>% 
  gt_fmt_cfb_wordmark(columns = c('Home_Team','Away_Team')) %>% 
  cols_align(
    align = c('center'),
    columns = everything()
  ) %>%   cols_label(
    Game_Total = md('**O/U**'),
    Home_Team = md('**Home**'),
    Home_Score = md('**Home Score**'), 
    Away_Score= md('**Away Score**'),
    Away_Team = md('**Away**'),
    Home_Spread = md('**Home Spread**')
  ) %>% 
  tab_header(
    title = md("**Vegas Lines**"),
    subtitle = md("Harrison Eller")
  ) %>% 
  fmt_number(
    columns = c(Home_Score, Away_Score, Game_Total, Home_Spread)
  ) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = c(Home_Score, Away_Score, Game_Total,Home_Spread)
    )
  )
```

## Model Output


```{r message=FALSE, warning=FALSE, include=FALSE}

if (include_scarlett == 'yes' || include_scarlett == 'y' ) {
team_plot_data <- invisible(CFB_MODEL(ht=ht,at=at,input_week=week,input_season=input_season,conferences = c(),previous_season=0,remove_fcs = TRUE))

home_team = ht
#y=team_plot_data
team_plot_data$conference = 0
team_plot_data<-team_plot_data %>% 
    filter(ht == home_team)


# team_plot_data$value_side = 'Army'


for(i in 1:nrow(team_plot_data)){
  team_plot_data$conference[i] = cfbd_stats_season_team(year = input_season, team = team_plot_data$ht[i])$conference
}

}
#team_plot_data$conference = 'NCAA'


# team_plot_data %>% 
#   transmute(Conference = conference, Home_Team = ht,
#             Home_Score = round(ht_score,2), 
#             Away_Score = round(at_score,2), Away_Team = at, Spread_Pick = value_side) %>% 
#   arrange(desc('Conference')) %>% 
#   gt() %>%
#   gt_fmt_cfb_logo(columns = c('Conference', 'Spread_Pick')) %>% 
#   gt_fmt_cfb_wordmark(columns = c('Home_Team','Away_Team')) %>% 
#   cols_align(
#     align = c('center'),
#     columns = everything()
#   ) %>%
#      cols_label(
#     Conference = md('**Conference**'),
#     Home_Team = md('**Home**'),
#     Home_Score = md('**Home Score**'), 
#     Away_Score= md('**Away Score**'),
#     Away_Team = md('**Away**'),
#     Spread_Pick= md('**Spread Pick**')
#   ) %>% 
#   tab_header(
#     title = md("**Scarlett Score Predictions**"),
#     subtitle = md("Harrison Eller")
#   ) %>% 
#   fmt_number(
#     columns = c(Home_Score, Away_Score)
#   ) %>%
#   tab_style(
#     style = list(
#       cell_text(weight = "bold")
#     ),
#     locations = cells_body(
#       columns = c(Home_Score, Away_Score)
#     )
#   )
```

```{r,echo=F}

if (include_scarlett == 'yes' || include_scarlett == 'y' ) {

team_plot_data %>% 
  transmute(Conference = conference, Home_Team = ht,
            Home_Score = round(ht_score,2), 
            Away_Score = round(at_score,2), Away_Team = at, Spread_Pick = value_side) %>% 
  arrange(desc('Conference')) %>% 
  gt() %>%
  gt_fmt_cfb_logo(columns = c('Conference', 'Spread_Pick')) %>% 
  gt_fmt_cfb_wordmark(columns = c('Home_Team','Away_Team')) %>% 
  cols_align(
    align = c('center'),
    columns = everything()
  ) %>%
     cols_label(
    Conference = md('**Conference**'),
    Home_Team = md('**Home**'),
    Home_Score = md('**Home Score**'), 
    Away_Score= md('**Away Score**'),
    Away_Team = md('**Away**'),
    Spread_Pick= md('**Spread Pick**')
  ) %>% 
  tab_header(
    title = md("**Scarlett Score Predictions**"),
    subtitle = md("Harrison Eller")
  ) %>% 
  fmt_number(
    columns = c(Home_Score, Away_Score)
  ) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = c(Home_Score, Away_Score)
    )
  )
}
```


# Team Comparison


```{r echo=F, message=FALSE, warning=FALSE}
tab <- TEAMS %>% 
    filter(team %in% c(ht,at)) %>% 
    select(team, Total_YPG, Passing_YPG,Rushing_YPG, Passing_YPA, Passing_YPC, Rushing_YPA, pass_TDs, rush_TDs, passes_intercepted, off_success_rate, off_explosiveness,off_power_success,off_passing_plays_success_rate, off_passing_plays_explosiveness, off_rushing_plays_success_rate, off_rushing_plays_explosiveness)
```

```{r, echo=F}
#  offensive comparison 
t <- TEAMS %>% 
    filter(team %in% c(ht,at))

t %>%
   select(team, conference.x, pass_TDs, rush_TDs,  interceptions,fumbles_lost,Total_YPG, Passing_YPG,Rushing_YPG, Passing_YPA, Passing_YPC, Rushing_YPA, third_down_conv_rate,off_success_rate, off_explosiveness,off_power_success,off_passing_plays_success_rate, off_passing_plays_explosiveness, off_rushing_plays_success_rate, off_rushing_plays_explosiveness) %>%
  transmute(Team = team, Passing_TDs = round(pass_TDs,0), Rushing_TDs = round(rush_TDs,0),  INTs = round(interceptions,0),FUM = round(fumbles_lost,0),Total_YPG, Passing_YPG,Rushing_YPG, Passing_YPA, Passing_YPC, Rushing_YPA, third_down_conv_rate) %>% 
gt(rowname_col = c("Team")) %>% 
  gt_fmt_cfb_logo(columns = c('Team')) %>% 
    cols_label(
    Team = md("**Team**"),
   Passing_TDs = md("**Pass TDs**"),
   Rushing_TDs = md("**Rush TDs**"),
   INTs = md("**INT**"),
   FUM = md("**FUM**"),
   Total_YPG = md("**YPG**"),
   Passing_YPG = md("**Pass YPG**"),
   Rushing_YPG = md("**Rush YPG**"),
    Passing_YPA = md("**Pass YPA**"),
    Passing_YPC = md("**Pass YPC**"),
    Rushing_YPA = md("**Rush YPA**"),
   third_down_conv_rate = md("**3D Conversion Rate**")
  ) %>% 
    fmt_number(
        columns = c(Passing_TDs,Rushing_TDs,INTs,FUM, Total_YPG, Passing_YPG,Rushing_YPG),
        decimals = 0
    ) %>% 
        fmt_number(
        columns = c(Passing_YPA, Passing_YPC, Rushing_YPA, third_down_conv_rate),
        decimals = 2
    ) %>% 
    data_color(
        columns = c(Passing_TDs),
        colors = scales::col_numeric(
            palette = c('red','white','green'),
            domain = c(min(TEAMS$pass_TDs),max(TEAMS$pass_TDs)
            )
        )
    ) %>% 
        data_color(
        columns = c(Rushing_TDs),
        colors = scales::col_numeric(
            palette = c('red','white','green'),
            domain = c(min(TEAMS$rush_TDs),max(TEAMS$rush_TDs)
            )
        )
    )  %>% 
        data_color(
        columns = c(INTs),
        colors = scales::col_numeric(
            palette = c('green','white','red'),
            domain = c(min(TEAMS$interceptions),max(TEAMS$interceptions)
            )
        )
    ) %>% 
        data_color(
        columns = c(FUM),
        colors = scales::col_numeric(
            palette = c('green','white','red'),
            domain = c(min(TEAMS$fumbles_lost),max(TEAMS$fumbles_lost)
            )
        )
    ) %>% 
        data_color(
        columns = c(Total_YPG),
        colors = scales::col_numeric(
            palette = c('red','white','green'),
            domain = c(min(TEAMS$Total_YPG),max(TEAMS$Total_YPG)
            )
        )
    )  %>% 
        data_color(
        columns = c(Passing_YPG),
        colors = scales::col_numeric(
            palette = c('red','white','green'),
            domain = c(min(TEAMS$Passing_YPG),max(TEAMS$Passing_YPG)
            )
        )
    ) %>% 
        data_color(
        columns = c(Rushing_YPG),
        colors = scales::col_numeric(
            palette = c('red','white','green'),
            domain = c(min(TEAMS$Rushing_YPG),max(TEAMS$Rushing_YPG)
            )
        )
    )%>% 
        data_color(
        columns = c(Passing_YPA),
        colors = scales::col_numeric(
            palette = c('red','white','green'),
            domain = c(min(TEAMS$Passing_YPA),max(TEAMS$Passing_YPA)
            )
        )
    )%>% 
        data_color(
        columns = c(Passing_YPC	),
        colors = scales::col_numeric(
            palette = c('red','white','green'),
            domain = c(min(TEAMS$Passing_YPC),max(TEAMS$Passing_YPC)
            )
        )
    )%>% 
        data_color(
        columns = c(Rushing_YPA	),
        colors = scales::col_numeric(
            palette = c('red','white','green'),
            domain = c(min(TEAMS$Rushing_YPA),max(TEAMS$Rushing_YPA)
            )
        )
    )%>% 
        data_color(
        columns = c(third_down_conv_rate),
        colors = scales::col_numeric(
            palette = c('red','white','green'),
            domain = c(min(TEAMS$third_down_conv_rate),max(TEAMS$third_down_conv_rate)
            )
        )
    ) %>% 
    tab_header(
    title = md("**Statistical Comparison**"),
    subtitle = md("2022 Season")
    ) %>% 
    tab_footnote(
    footnote = "YPG = Yards Per Game",
    locations = cells_column_labels(
      columns = c(Total_YPG, Passing_YPG, Rushing_YPG)
    )
) %>% 
    tab_footnote(
    footnote = "YPA = Yards Per Attempt",
    locations = cells_column_labels(
      columns = c(Passing_YPA, Rushing_YPA)
    )
)  %>% 
    tab_footnote(
    footnote = "YPC = Yards Per Completion",
    locations = cells_column_labels(
      columns = c(Passing_YPC)
    )
)









```

```{r, echo=F}
# TEAMS %>%
#    filter(team %in% c(ht,at)) %>% 
#    select(team,  off_success_rate, off_explosiveness,off_power_success,off_passing_plays_success_rate, off_passing_plays_explosiveness, off_rushing_plays_success_rate, off_rushing_plays_explosiveness
# ) %>%
#   transmute(Team= team, off_success_rate, off_explosiveness,off_power_success,off_passing_plays_success_rate, off_passing_plays_explosiveness, off_rushing_plays_success_rate, off_rushing_plays_explosiveness) %>% 
# gt(rowname_col = c("Team")) %>% 
#   gt_fmt_cfb_logo(columns = c(Team)) %>% 
#         fmt_number(
#         columns = c(off_success_rate, off_explosiveness,off_power_success,off_passing_plays_success_rate, off_passing_plays_explosiveness, off_rushing_plays_success_rate, off_rushing_plays_explosiveness),
#         decimals = 2
#     )
# 



off_ratings <- TEAMS %>% 
    filter(team %in% c(ht,at))

off_ratings %>%
   select(team, conference.x, pass_TDs, rush_TDs,  passes_intercepted,fumbles_lost,Total_YPG, Passing_YPG,Rushing_YPG, Passing_YPA, Passing_YPC, Rushing_YPA, off_success_rate, off_explosiveness,off_power_success,off_passing_plays_success_rate, off_passing_plays_explosiveness, off_rushing_plays_success_rate, off_rushing_plays_explosiveness) %>%
  transmute(Team= team, off_success_rate, off_explosiveness,off_power_success,off_passing_plays_success_rate, off_passing_plays_explosiveness, off_rushing_plays_success_rate, off_rushing_plays_explosiveness) %>% 
gt(rowname_col = c("Team")) %>% 
  gt_fmt_cfb_logo(columns = c('Team')) %>% 
    cols_label(
    Team = md("**Team**"),
   off_success_rate = md("**Success Rate**"),
   off_explosiveness = md("**Explosiveness**"),
   off_power_success = md("**Power Success**"),
   off_passing_plays_success_rate = md("**Pass SR**"),
   off_passing_plays_explosiveness = md("**Pass EXP**"),
   off_rushing_plays_success_rate = md("**Rush SR**"),
   off_rushing_plays_explosiveness = md("**Rush EXP**"),
  ) %>% 
        fmt_number(
        columns = c(off_success_rate, off_explosiveness, off_power_success,off_passing_plays_success_rate,off_passing_plays_explosiveness,off_rushing_plays_success_rate,off_rushing_plays_explosiveness),
        decimals = 2
    ) %>% 
    data_color(
        columns = c(off_success_rate),
        colors = scales::col_numeric(
            palette = c('red','white','green'),
            domain = c(min(TEAMS$off_success_rate,na.rm = TRUE),max(TEAMS$off_success_rate,na.rm = TRUE)
            )
        )
    ) %>% 
        data_color(
        columns = c(off_explosiveness),
        colors = scales::col_numeric(
            palette = c('red','white','green'),
            domain = c(min(TEAMS$off_explosiveness,na.rm = TRUE),max(TEAMS$off_explosiveness,na.rm = TRUE)
            )
        )
    )  %>% 
        data_color(
        columns = c(off_power_success),
        colors = scales::col_numeric(
            palette = c('red','white','green'),
            domain = c(min(TEAMS$off_power_success,na.rm = TRUE),max(TEAMS$off_power_success,na.rm = TRUE)
            )
        )
    ) %>% 
        data_color(
        columns = c(off_passing_plays_success_rate),
        colors = scales::col_numeric(
            palette = c('red','white','green'),
            domain = c(min(TEAMS$off_passing_plays_success_rate,na.rm = TRUE),max(TEAMS$off_passing_plays_success_rate,na.rm = TRUE)
            )
        )
    ) %>% 
        data_color(
        columns = c(off_passing_plays_explosiveness),
        colors = scales::col_numeric(
            palette = c('red','white','green'),
            domain = c(min(TEAMS$off_passing_plays_explosiveness,na.rm = TRUE),max(TEAMS$off_passing_plays_explosiveness,na.rm = TRUE)
            )
        )
    ) %>% 
    data_color(
        columns = c(off_rushing_plays_success_rate),
        colors = scales::col_numeric(
            palette = c('red','white','green'),
            domain = c(min(TEAMS$off_rushing_plays_success_rate,na.rm = TRUE),max(TEAMS$off_rushing_plays_success_rate,na.rm = TRUE)
            )
        )
    ) %>% 
    data_color(
        columns = c(off_rushing_plays_explosiveness),
        colors = scales::col_numeric(
            palette = c('red','white','green'),
            domain = c(min(TEAMS$off_rushing_plays_explosiveness,na.rm = TRUE),max(TEAMS$off_rushing_plays_explosiveness,na.rm = TRUE)
            )
        )
    ) %>% 
    tab_header(
    title = md("**Offensive Ratings Comparison**"),
    subtitle = md("2022 Season")
    )  %>% 
    tab_footnote(
    footnote = "SR = Success Rate",
    locations = cells_column_labels(
      columns = c(off_passing_plays_success_rate,off_rushing_plays_success_rate)
    )
)%>% 
    tab_footnote(
    footnote = "EXP = Explosiveness",
    locations = cells_column_labels(
      columns = c(off_passing_plays_explosiveness,off_rushing_plays_explosiveness)
    )
)






```

```{r, echo=F}
## Defesnive Breakdown
def_ratings <- TEAMS %>% 
    filter(team %in% c(ht,at))

def_ratings %>%
   select(team, conference.x, def_success_rate, def_explosiveness,def_power_success,def_passing_plays_success_rate, def_passing_plays_explosiveness, def_rushing_plays_success_rate, def_rushing_plays_explosiveness) %>%
  transmute(Team= team, def_success_rate, def_explosiveness,def_power_success,def_passing_plays_success_rate, def_passing_plays_explosiveness, def_rushing_plays_success_rate, def_rushing_plays_explosiveness) %>% 
gt(rowname_col = c("Team")) %>% 
  gt_fmt_cfb_logo(columns = c('Team')) %>% 
    cols_label(
    Team = md("**Team**"),
   def_success_rate = md("**Success Rate**"),
   def_explosiveness = md("**Explosiveness**"),
   def_power_success = md("**Power Success**"),
   def_passing_plays_success_rate = md("**Pass SR**"),
   def_passing_plays_explosiveness = md("**Pass EXP**"),
   def_rushing_plays_success_rate = md("**Rush SR**"),
   def_rushing_plays_explosiveness = md("**Rush EXP**"),
  ) %>% 
        fmt_number(
        columns = c(def_success_rate, def_explosiveness,def_power_success,def_passing_plays_success_rate, def_passing_plays_explosiveness, def_rushing_plays_success_rate, def_rushing_plays_explosiveness),
        decimals = 2
    ) %>% 
    data_color(
        columns = c(def_success_rate),
        colors = scales::col_numeric(
            palette = c('green','white','red'),
            domain = c(min(TEAMS$def_success_rate,na.rm = TRUE),max(TEAMS$def_success_rate,na.rm = TRUE)
            )
        )
    ) %>% 
        data_color(
        columns = c(def_explosiveness),
        colors = scales::col_numeric(
            palette = c('green','white','red'),
            domain = c(min(TEAMS$def_explosiveness,na.rm = TRUE),max(TEAMS$def_explosiveness,na.rm = TRUE)
            )
        )
    )  %>% 
        data_color(
        columns = c(def_power_success),
        colors = scales::col_numeric(
            palette = c('green','white','red'),
            domain = c(min(TEAMS$def_power_success,na.rm = TRUE),max(TEAMS$def_power_success,na.rm = TRUE)
            )
        )
    ) %>% 
        data_color(
        columns = c(def_passing_plays_success_rate),
        colors = scales::col_numeric(
            palette = c('green','white','red'),
            domain = c(min(TEAMS$def_passing_plays_success_rate,na.rm = TRUE),max(TEAMS$def_passing_plays_success_rate,na.rm = TRUE)
            )
        )
    ) %>% 
        data_color(
        columns = c(def_passing_plays_explosiveness),
        colors = scales::col_numeric(
            palette = c('green','white','red'),
            domain = c(min(TEAMS$def_passing_plays_explosiveness,na.rm = TRUE),max(TEAMS$def_passing_plays_explosiveness,na.rm = TRUE)
            )
        )
    ) %>% 
    data_color(
        columns = c(def_rushing_plays_success_rate),
        colors = scales::col_numeric(
            palette = c('green','white','red'),
            domain = c(min(TEAMS$def_rushing_plays_success_rate,na.rm = TRUE),max(TEAMS$def_rushing_plays_success_rate,na.rm = TRUE)
            )
        )
    ) %>% 
    data_color(
        columns = c(def_rushing_plays_explosiveness),
        colors = scales::col_numeric(
            palette = c('green','white','red'),
            domain = c(min(TEAMS$def_rushing_plays_explosiveness,na.rm = TRUE),max(TEAMS$def_rushing_plays_explosiveness,na.rm = TRUE)
            )
        )
    ) %>% 
    tab_header(
    title = md("**Defensive Ratings Comparison**"),
    subtitle = md("2022 Season")
    )  %>% 
    tab_footnote(
    footnote = "SR = Success Rate",
    locations = cells_column_labels(
      columns = c(def_passing_plays_success_rate,def_rushing_plays_success_rate)
    )
)%>% 
    tab_footnote(
    footnote = "EXP = Explosiveness",
    locations = cells_column_labels(
      columns = c(def_passing_plays_explosiveness,def_rushing_plays_explosiveness)
    )
)





```

## EPA Comparison

```{r pressure, echo=FALSE, fig.align='center', message=FALSE, warning=FALSE}
# gather data 
pbp <- cfbfastR::load_cfb_pbp(input_season) %>% 
  filter(week == week)

team_info <- cfbfastR::cfbd_team_info()
team_info <- team_info %>% 
  select(team = school,conference,mascot) %>% 
  filter(conference %in% c("Pac-12","ACC","SEC","Big Ten","Big 12"))


team_plot_data <- pbp %>% 
  group_by(team = offense_play) %>% 
  summarize(rush_epa = mean(if_else(rush == 1,EPA,NA_real_),na.rm = TRUE),
            n_rush = sum(rush),
            pass_epa = mean(if_else(pass == 1,EPA,NA_real_),na.rm = TRUE),
            n_pass = sum(pass)) %>% 
  filter(team %in% team_info$team) %>% 
  left_join(team_info,by = "team")


team_plot_data %>% 
  mutate(color = if_else(team %in% c(ht,at),NA_character_,"b/w"),
         alpha = if_else(team %in% c(ht,at),1,.6)) %>% 
  ggplot(aes(x = pass_epa, y = rush_epa)) +
  geom_median_lines(aes(v_var = pass_epa, h_var = rush_epa)) +
  geom_cfb_logos(aes(team = team, alpha = alpha, color = color), width = 0.075) +
  scale_alpha_identity() +
  scale_color_identity() +
  labs(x = "EPA per Pass",y = "EPA per Rush") +
  theme_bw()
```
